### ISSUE TITLE
Wrong URL to pull data

### ISSUE THREAD

**Issue by RonEskinder** [roclark/basketball-predictor#18]
`iMac:~ roneskinder$ docker run --rm -it roclark/clarktech-ncaab-predictor daily-simulation

    WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

    /usr/local/lib/python3.7/site-packages/sklearn/externals/six.py:31: DeprecationWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
      "(https://pypi.org/project/six/).", DeprecationWarning)
    Traceback (most recent call last):
       File "./run-simulator.py", line 789, in <module>
        main()
      File "./run-simulator.py", line 782, in main
    teams = Teams()
      File "/usr/local/lib/python3.7/site-packages/sportsreference/ncaab/teams.py", line 997, in __init__
    self._conferences_dict = Conferences(year).team_conference
      File "/usr/local/lib/python3.7/site-packages/sportsreference/ncaab/conferences.py", line 142, in __init__
    self._find_conferences(year)
      File "/usr/local/lib/python3.7/site-packages/sportsreference/ncaab/conferences.py", line 218, in _find_conferences
    raise ValueError(output)

    ValueError: Can't pull requested conference page. Ensure the following URL exists: https://www.sports-reference.com/cbb/seasons/2023.html`

**Comment by mtoconno** [comment]
@RonEskinder , there's a few issues going on here, which I can summarize as follows:
1) the `sportsreference` package was renamed `sportsipy` (see https://github.com/roclark/sportsipy)
2) it looks like at some point sports-reference.com completely redesigned their website (as far as the NCAA MBB portion is concerned), so many of the URLs have changed and the formatting of the data has also completely changed.

I looked into it to see how much it has changed, and unfortunately, it's changed a lot.  Fixing the `sportsipy` package to run any portion of the ncaab predictor would require a complete rewrite.
